### ISSUE TITLE
Computing v' in Appendix B

### ISSUE THREAD

**Issue by chentingpc** [duvenaud/relax#1]
Dear authors,

Thanks for sharing your code. I noticed a difference between the code and paper in computing \tilde{z}. Specifically, in the [code](https://github.com/duvenaud/relax/blob/198bbb36efd4f4fc2d1289a0c277bb8f90ebe8b7/relax-autograd/relax.py#L30) 1-\theta is performed, but in Appendix B of the paper when computing v', \theta is directly used. Is the latter a typo, or am I missing something?

Thanks

**Comment by duvenaud** [comment]
Good catch, thanks!  It was a typo in the paper, which is now fixed.
